### ISSUE TITLE
Make a very simple website

### ISSUE THREAD

**Issue by r-arvind** [r-arvind/hyperspace.js#1]
Build a really simple website using hyperspace.js. 
The docs folder already has a simple website with "Coming Soon" written. Fell free to modify it and make it better.

**Comment by MaanasVohra** [comment]
Could you help me out on this? The README.md file doesn't show the description of what the library does or intends to do, so it would be difficult to describe what the website should show.

**Comment by r-arvind** [comment]
My bad.
@MaanasVohra, @FedeX15  I have updated the Readme.

**Comment by r-arvind** [comment]
I'll give a brief explanation of what i want. So, I intended this library to be like [particles.js](https://github.com/VincentGarreau/particles.js/) where you can use it to animate your website. All I want is some sort of a demo website to display its usage.
Currently, I have hosted a website at my [gh-pages](https://r-arvind.github.io/hyperspace.js) which says "Coming Soon". I want to replace it with a better website

**Comment by visv-in** [comment]
Hi, I have made changes on the existing website and made a pull request, please have a look into it. Here is the image that shows how it looks.
![screenshot_2018-10-07 hyperspace js](https://user-images.githubusercontent.com/20577139/46583440-eca42e80-ca74-11e8-96e6-93258c6de40f.png)

**Comment by r-arvind** [comment]
Thank @visvxplore . It looks amazing.

**Comment by r-arvind** [comment]
This issue has been fixed.
